


node {
	stage("checkout"){
		 git url: 'https://github.com/nagabhushanamn/shopIT-micro-services.git',branch: 'master' 
	}
	stage("compile and test"){
		def path="shopIT-products-catalog";
		dir(path){
			sh "mvn clean test"
		}
	}
}

