


node {
	def path="shopIT-products-catalog";
	stage("checkout"){
		 git url: 'https://github.com/nagabhushanamn/shopIT-micro-services.git',branch: 'master' 
	}
	stage("build"){
		dir(path){
			sh "mvn clean test"
		}
	}
	stage('package') {
     	dir(path){
     		sh 'mvn package'
     	}
     }
     stage('deploy-to-QA') {
     	
     }
     stage('deploy') {
     	
     }
}

	