


node {
	def path="shopIT-accounts-service";
	stage("checkout"){
		 git url: 'https://github.com/nagabhushanamn/shopIT-micro-services.git',branch: 'master' 
	}
	stage("build"){
		dir(path){
			sh "mvn clean test"
		}
	}
	stage('package') {
     	dir(path){
     		sh 'mvn package'
     	}
     }
}

	